name: "Send Email After Workflow"

on:
  workflow_dispatch:


jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v5

      - name: "Setup Python Environment"
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
     
      - name: "Send Email"
        run: python script.py
        env:
          WORKFLOW_NAME: ${{ github.Workflow }}
          REPOSITORY_NAME: ${{ github.Repository }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIEVER_EMAIL: ${{ secrets.RECIEVER_EMAIL }}
